package lk.ijse.MobiCity.util;

public enum Routes {
    LOG,USERDASHBOARD,ADMINDASHBOARD,EMPLOYEE,ADDEMPLOYEE,DELETEEMPLOYEE,UPDATEEMPLOYEE,SEARCHEMPLOYEE,USER,UPDATEUSER,SEARCHUSER,DELETEUSER,PLACEORDER,
    CUSTOMER,UPDATECUSTOMER,DELETECUSTOMER,SEARCHCUSTOMER,SUPPLIER,SEARCHSUPPLIER,DELETESUPPLIER,UPDATESUPPLIER,ORDER,ITEM,UPDATEITEM,DELETEITEM,SEARCHITEM
}
